---
framework: jest
preRun:
     command:
        - npm install
        - npm run react
preMerge:
  pattern:
    - "test/slider-test.jsx"
    - "test/algorithms/geometric-test.js"
postMerge:
  pattern:
    - "test/slider-test.jsx"
    - "test/algorithms/geometric-test.js"
version: 1.0
