---
framework: jestJ
preRun:
     command:
        - npm install
        - npm run react
preMerge:
  pattern:
    - "./test/slider-test.js"
    - "./test/algorithms/*.test.js"
postMerge:
  pattern:
    - "./test/slider-test.js"
    - "./test/algorithms/*.test.js"
version: 1.0
